import styles from "@/styles/DoctorList.module.scss";
import Head from "next/head";
import Link from "next/link";

import DoctorCardsColumn from "@/components/doctorCardsColumn";

import { IoIosArrowBack } from "react-icons/io";

export default function DoctorList() {
  return (
    <>
      <Head>
        <title>Appointment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="theme-color" content="#1dbab5" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.DoctorList}>
        <nav className={styles.navTitle}>
          <span className={styles.iconBack}>
            <Link href="/intro">
              <IoIosArrowBack />
            </Link>
          </span>
          <div className={styles.titleCenter}>
            <h1>All Doctors</h1>
          </div>
        </nav>
        <DoctorCardsColumn />
      </main>
    </>
  );
}
