import Head from "next/head";
import styles from "@/styles/Intro.module.scss";

export default function intro() {
  return (
    <>
      <Head>
        <title>Appointment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="theme-color" content="#1dbab5" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>ciao</main>
    </>
  );
}
