import Head from "next/head";
import styles from "@/styles/Intro.module.scss";

import Image from "next/image";
import { useState } from "react";

export default function intro() {
  const [imgNext, setImageNext] = useState(1);
  const [isStartPage, setStartPage] = useState(false);

  const onHandleBtnNext = () => {
    setImageNext((prev) => prev + 1);
    setStartPage(imgNext === 2);
  };

  return (
    <>
      <Head>
        <title>Appointment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta name="theme-color" content="#1dbab5" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!isStartPage && (
          <>
            <Image
              width={100}
              height={100}
              src={`/${imgNext}.svg`}
              alt="Descrizione dell'immagine"
            />
            {imgNext === 1 ? (
              <h1>Book your Appointment</h1>
            ) : (
              <h1>Get a prescription from a Doctor</h1>
            )}
            <button className={styles.btnNext} onClick={onHandleBtnNext}>
              Next
            </button>
          </>
        )}

        {isStartPage && <h1>Benvenuto nella pagina</h1>}
      </main>
    </>
  );
}
